import React from 'react';
import type { RenderMode, TabBarType, TabBarPosition, KeyboardDismissMode, JumpMode } from '../types/TabView';
import type { HeaderRendererProps, NavigationState, SceneRendererProps } from '../types/common';
import type { ViewStyle } from 'react-native';
import type { StyleProp } from 'react-native';
import type { TabBarProps } from '../types';
import type { SharedValue } from 'react-native-reanimated';
import type { TextStyle } from 'react-native';
type PropsContext = {
    navigationState: NavigationState;
    renderMode: RenderMode;
    tabBarType: TabBarType;
    tabBarPosition: TabBarPosition;
    tabBarScrollEnabled: boolean;
    tabBarDynamicWidthEnabled: boolean;
    tabBarIndicatorStyle: StyleProp<ViewStyle>;
    tabBarStyle: StyleProp<ViewStyle>;
    tabStyle: StyleProp<ViewStyle>;
    tabLabelStyle: StyleProp<TextStyle>;
    scrollableTabWidth: number;
    swipeEnabled: boolean;
    jumpMode: JumpMode;
    sceneContainerGap: number;
    sceneContainerStyle: StyleProp<ViewStyle>;
    tabViewCarouselStyle: StyleProp<ViewStyle>;
    keyboardDismissMode?: KeyboardDismissMode;
    providedAnimatedRouteIndexSV?: SharedValue<number>;
    renderTabBar?: (props: TabBarProps) => React.ReactNode;
    renderScene: (props: SceneRendererProps) => React.ReactNode;
    renderHeader?: (props: HeaderRendererProps) => React.ReactNode;
    onIndexChange?: (index: number) => void;
    onSwipeEnd?: () => void;
    onSwipeStart?: () => void;
    refreshing?: boolean;
    onRefresh?: () => void;
    refreshControlColor?: string;
};
declare const PropsContext: React.Context<PropsContext>;
type PropsContextProviderProps = {
    value: PropsContext;
};
export declare const PropsContextProvider: React.NamedExoticComponent<React.PropsWithChildren<PropsContextProviderProps>>;
export declare const usePropsContext: () => PropsContext;
export {};
//# sourceMappingURL=Props.d.ts.map